# Generated by Django 5.1.4 on 2024-12-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetConnecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type_objet', models.CharField(choices=[('CAPTEUR', 'Capteur'), ('ACTIONNEUR', 'Actionneur'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('etat', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('MAINTENANCE', 'En maintenance')], default='INACTIF', max_length=20)),
                ('date_installation', models.DateField()),
                ('derniere_maintenance', models.DateField(blank=True, null=True)),
                ('localisation', models.CharField(max_length=200)),
            ],
        ),
    ]
